# -*- indent-tabs-mode: nil -*-

image: fedora:27

stages:
  - test

before_script:
  - dnf install -y gcc rust cargo
                   automake autoconf libtool gettext itstool
                   gtk-doc
                   redhat-rpm-config git
                   gobject-introspection-devel
                   libxml2-devel
                   libcroco-devel
                   cairo-devel
                   pango-devel
                   gdk-pixbuf2-devel
                   gtk3-devel

test:
  stage: test
  script:
    - ./autogen.sh --enable-debug
    - make check

  artifacts:
    when: on_failure
    paths:
      - /tmp/*.png
      - tests/*.log
