image: fedora:27

stages:
  - test

before_script:
  - dnf install -y gcc rust cargo
                   automake autoconf libtool gettext itstool
                   gtk-doc
                   redhat-rpm-config git
                   gtk3-devel
                   gobject-introspection-devel
                   libxml2-devel

test:
  stage: test
  script:
    - ./autogen.sh --enable-debug
    - make check
