[package]
name = "pixbufloader-svg"
version = "0.0.1"
authors = ["Alberto Ruiz <aruiz@gnome.org>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
librsvg = { path = ".." }
gdk-pixbuf = "0.17"
libc = "0.2"
glib = "0.17"
gio = "0.17"
cairo-rs = "0.17"
cstr = "0.2"