[package]
name = "pixbufloader-svg"
version = "0.0.1"
authors = ["Alberto Ruiz <aruiz@gnome.org>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
gdk-pixbuf-sys = "0.15"
libc = "0.2"
glib-sys = "0.15"
gobject-sys = "0.15"
glib = "0.15"
cstr = "0.2"