[package]
name = "pixbufloader-svg"
version = "0.0.1"
authors = ["Alberto Ruiz <aruiz@gnome.org>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
librsvg = { path = ".." }
gdk-pixbuf-sys = "0.16"
gdk-pixbuf = "0.16"
libc = "0.2"
glib-sys = "0.16"
gobject-sys = "0.16"
glib = "0.16"
gio = "0.16"
cairo-rs = "0.16"
cstr = "0.2"