[package]
name = "rsvg_internals"
version = "0.0.1"
authors = ["Federico Mena Quintero <federico@gnome.org>"]
workspace = "../"
build = "build.rs"

# IMPORTANT: If you add/remove/update dependencies here, please also
# update Cargo.toml in https://gitlab.com/BuildStream/cargo-fetcher
# (just submit a merge request there).
#
# BuildStream/cargo-fetcher lets GNOME's BuildStream continuous build
# service know which dependencies are required.
#
# Please update your dependencies here, then run "cargo update" to
# regenerate librsvg/Cargo.lock, and copy the resolved version numbers
# from there into cargo-fetcher/Cargo.toml.

[build-dependencies]
phf_codegen = "0.7.21"

[dependencies]
cairo-rs = { git="https://github.com/gtk-rs/cairo", branch="master" }
cairo-sys-rs = { git="https://github.com/gtk-rs/cairo", branch="master" }
cssparser = "0.25.1"
data-url = "0.1"
downcast-rs = "^1.0.0"
encoding = "0.2.33"
float-cmp = "0.4.0"
gdk-pixbuf = { git="https://github.com/gtk-rs/gdk-pixbuf", branch="master" }
gdk-pixbuf-sys = { git="https://github.com/gtk-rs/sys", branch="master" }
gio = { git="https://github.com/gtk-rs/gio", branch="master", features=["v2_48"] } # per configure.ac
gio-sys = { git="https://github.com/gtk-rs/sys", branch="master" }
glib = { git="https://github.com/gtk-rs/glib", branch="master", features=["subclassing"] }
glib-sys = { git="https://github.com/gtk-rs/sys", branch="master" }
gobject-sys = { git="https://github.com/gtk-rs/sys", branch="master" }
itertools = "0.7.4"
language-tags = "0.2.2"
lazy_static = "1.0.0"
libc = "0.2"
locale_config = "*" # recommended explicitly by locale_config's README.md
nalgebra = "0.16"
num-traits = "0.2"
owning_ref = "0.4.0"
pango = { git="https://github.com/gtk-rs/pango", branch="master" }
pango-sys = { git="https://github.com/gtk-rs/sys", branch="master" }
pangocairo = { git="https://github.com/gtk-rs/pangocairo", branch="master" }
phf = "0.7.21"
rayon = "1"
regex = "1"
url = "1.7.2"
xml-rs = "0.8.0"

[dev-dependencies]
criterion = "0.2"

[lib]
name = "rsvg_internals"
crate-type = ["staticlib", "lib"]

[[bench]]
name = "box_blur"
harness = false

[[bench]]
name = "composite"
harness = false

[[bench]]
name = "lighting"
harness = false

[[bench]]
name = "pixel_iterators"
harness = false

[[bench]]
name = "srgb"
harness = false
