[package]
name = "rsvg_internals"
version = "0.0.1"
authors = ["Federico Mena Quintero <federico@gnome.org>"]

[dependencies]
libc = "0.2"
cairo-rs = { git = "https://github.com/federicomenaquintero/cairo.git" }

[lib]
name = "rsvg_internals"
crate-type = ["staticlib"]
