[package]
name = "rsvg_internals"
version = "0.0.1"
authors = ["Federico Mena Quintero <federico@gnome.org>"]
build = "build.rs"

[dependencies]
libc = "0.2"
bitflags = ""

[dependencies.cairo-sys-rs]
#git = "https://github.com/gtk-rs/cairo.git"
git = "https://github.com/federicomenaquintero/cairo.git"
#branch = "matrix-try-invert"
#git = "file:///home/federico/src/gtk-rs/cairo"
#features = ["png"]

[dependencies.cairo-rs]
#git = "https://github.com/gtk-rs/cairo.git"
git = "https://github.com/federicomenaquintero/cairo.git"
#branch = "matrix-try-invert"
#git = "file:///home/federico/src/gtk-rs/cairo"
#features = ["png"]

[dependencies.glib]
git = "https://github.com/gtk-rs/glib"
version = "0.1.1"

[dependencies.glib-sys]
git = "https://github.com/gtk-rs/sys"
version = "0.3.2"

[dependencies.nom]
#git = "https://github.com/Geal/nom"
git = "https://github.com/federicomenaquintero/nom.git"
features = ["verbose-errors"]

[dependencies.downcast-rs]
git = "https://github.com/marcianx/downcast-rs"
version = "1.0.0"

[dependencies.regex]
version = "0.2.1"

[dependencies.lalrpop-util]
version = "0.12.5"

[build-dependencies.lalrpop]
version = "0.12.5"

[lib]
name = "rsvg_internals"
crate-type = ["staticlib"]
